name: Veracode SCA Scan
#
on: 
  push:
    paths-ignore:
      - "README.md"
#  schedule:
#    - cron: 15 14 * * 6

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
        with: 
          java-version: '8'

      - name: Build with Maven
        run: mvn -B package --file /.m2/app/target/pom.xml

      - uses: actions/upload-artifact@v2 # Copy files from repository to docker container so the next uploadandscan action can access them.
        with:
          path: '**/*.war' # Wildcards can be used to filter the files copied into the container. See: https://github.com/actions/upload-artifact
      - name: Veracode Software Composition Analysis
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          run: |
            curl -sSL https://download.sourceclear.com/ci.sh | sh -s -- scan --debug --allow-dirty
        uses: mokkang/verademo-sca@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          quick: false
          debug: false
          create-issues: true 
          fail-on-cvss: 1
          min-cvss-for-issue: 1
          path: '~/app/target/verademo.war'
    
        
            
